"""Self-contained HTML report generator for Sentinel findings."""
from __future__ import annotations

import html
from datetime import datetime, timezone
from typing import Any

from sentinel.reporters.base import BaseReporter

_SEVERITY_COLORS = {
    "critical": "#dc2626",
    "high": "#ea580c",
    "medium": "#ca8a04",
    "low": "#16a34a",
    "info": "#2563eb",
}

_SEVERITY_ORDER = ["critical", "high", "medium", "low", "info"]


def _sev(finding) -> str:
    return getattr(getattr(finding, "severity", None), "value", str(getattr(finding, "severity", "info"))).lower()


class HtmlReporter(BaseReporter):
    """Generate a self-contained HTML report with severity summary and findings table."""

    def generate(self, findings: list, metadata: dict[str, Any] | None = None) -> str:
        meta = metadata or {}
        scan_path = html.escape(str(meta.get("scan_path", ".")))
        tool_version = html.escape(str(meta.get("tool_version", "Eresus Sentinel")))
        timestamp = meta.get("timestamp") or datetime.now(timezone.utc).isoformat()

        counts: dict[str, int] = {s: 0 for s in _SEVERITY_ORDER}
        for f in findings:
            counts[_sev(f)] = counts.get(_sev(f), 0) + 1

        pie_slices = _build_pie(counts)
        rows = _build_rows(findings)
        summary_cards = _build_summary_cards(counts)

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Eresus Sentinel — Security Report</title>
<style>
  body {{ font-family: system-ui, -apple-system, sans-serif; margin: 0; background: #f8fafc; color: #1e293b; }}
  header {{ background: #0f172a; color: #f1f5f9; padding: 1.5rem 2rem; }}
  header h1 {{ margin: 0; font-size: 1.5rem; }}
  header p {{ margin: 0.25rem 0 0; color: #94a3b8; font-size: 0.875rem; }}
  .container {{ max-width: 1200px; margin: 2rem auto; padding: 0 1.5rem; }}
  .summary {{ display: flex; gap: 1rem; flex-wrap: wrap; margin-bottom: 2rem; }}
  .card {{ background: #fff; border-radius: 0.75rem; padding: 1rem 1.5rem; flex: 1; min-width: 120px;
           box-shadow: 0 1px 3px rgba(0,0,0,0.1); border-left: 4px solid var(--c); }}
  .card .count {{ font-size: 2rem; font-weight: 700; color: var(--c); }}
  .card .label {{ font-size: 0.75rem; text-transform: uppercase; color: #64748b; letter-spacing: 0.05em; }}
  .chart-section {{ background: #fff; border-radius: 0.75rem; padding: 1.5rem;
                    box-shadow: 0 1px 3px rgba(0,0,0,0.1); margin-bottom: 2rem;
                    display: flex; align-items: center; gap: 2rem; }}
  svg.pie {{ width: 160px; height: 160px; flex-shrink: 0; }}
  .legend {{ display: flex; flex-direction: column; gap: 0.5rem; }}
  .legend-item {{ display: flex; align-items: center; gap: 0.5rem; font-size: 0.875rem; }}
  .legend-dot {{ width: 12px; height: 12px; border-radius: 50%; flex-shrink: 0; }}
  table {{ width: 100%; border-collapse: collapse; background: #fff; border-radius: 0.75rem;
           box-shadow: 0 1px 3px rgba(0,0,0,0.1); overflow: hidden; }}
  th {{ background: #f1f5f9; padding: 0.75rem 1rem; text-align: left; font-size: 0.75rem;
        text-transform: uppercase; color: #64748b; letter-spacing: 0.05em; }}
  td {{ padding: 0.75rem 1rem; border-top: 1px solid #e2e8f0; font-size: 0.875rem; vertical-align: top; }}
  tr:hover td {{ background: #f8fafc; }}
  .badge {{ display: inline-block; padding: 0.2rem 0.5rem; border-radius: 9999px; font-size: 0.7rem;
            font-weight: 600; text-transform: uppercase; color: #fff; }}
  .code {{ font-family: monospace; font-size: 0.8rem; background: #f1f5f9; padding: 0.1rem 0.3rem;
           border-radius: 0.25rem; word-break: break-all; }}
  .no-findings {{ text-align: center; padding: 3rem; color: #64748b; }}
  footer {{ text-align: center; padding: 2rem; color: #94a3b8; font-size: 0.75rem; }}
</style>
</head>
<body>
<header>
  <h1>🛡️ Eresus Sentinel — Security Report</h1>
  <p>Scan path: {scan_path} &nbsp;|&nbsp; Generated: {html.escape(timestamp)} &nbsp;|&nbsp; {tool_version}</p>
</header>
<div class="container">
  <div class="summary">{summary_cards}</div>
  <div class="chart-section">
    <svg class="pie" viewBox="0 0 160 160">{pie_slices}</svg>
    <div class="legend">{_build_legend(counts)}</div>
  </div>
  {"<table>" + _TABLE_HEADER + "<tbody>" + rows + "</tbody></table>" if findings else '<div class="no-findings">✅ No findings — scan clean.</div>'}
</div>
<footer>Generated by Eresus Sentinel &nbsp;·&nbsp; {html.escape(timestamp)}</footer>
</body>
</html>"""


_TABLE_HEADER = """<thead><tr>
  <th>Severity</th><th>Rule ID</th><th>Title</th>
  <th>Target</th><th>Description</th>
</tr></thead>"""


def _build_rows(findings: list) -> str:
    rows: list[str] = []
    for f in sorted(findings, key=lambda x: _SEVERITY_ORDER.index(_sev(x)) if _sev(x) in _SEVERITY_ORDER else 99):
        sev = _sev(f)
        color = _SEVERITY_COLORS.get(sev, "#64748b")
        rule_id = html.escape(str(getattr(f, "rule_id", "")))
        title = html.escape(str(getattr(f, "title", "")))
        target = html.escape(str(getattr(f, "target", "")))
        description = html.escape(str(getattr(f, "description", "")))
        rows.append(
            f'<tr><td><span class="badge" style="background:{color}">{html.escape(sev)}</span></td>'
            f'<td><span class="code">{rule_id}</span></td>'
            f'<td>{title}</td>'
            f'<td><span class="code">{target}</span></td>'
            f'<td>{description}</td></tr>'
        )
    return "".join(rows)


def _build_summary_cards(counts: dict[str, int]) -> str:
    cards: list[str] = []
    for sev in _SEVERITY_ORDER:
        c = counts.get(sev, 0)
        color = _SEVERITY_COLORS[sev]
        cards.append(
            f'<div class="card" style="--c:{color}">'
            f'<div class="count">{c}</div>'
            f'<div class="label">{sev.capitalize()}</div></div>'
        )
    cards.append(
        f'<div class="card" style="--c:#475569">'
        f'<div class="count">{sum(counts.values())}</div>'
        f'<div class="label">Total</div></div>'
    )
    return "".join(cards)


def _build_legend(counts: dict[str, int]) -> str:
    items: list[str] = []
    for sev in _SEVERITY_ORDER:
        c = counts.get(sev, 0)
        color = _SEVERITY_COLORS[sev]
        items.append(
            f'<div class="legend-item">'
            f'<div class="legend-dot" style="background:{color}"></div>'
            f'{html.escape(sev.capitalize())}: {c}</div>'
        )
    return "".join(items)


def _build_pie(counts: dict[str, int]) -> str:
    total = sum(counts.values())
    if total == 0:
        return '<circle cx="80" cy="80" r="70" fill="#e2e8f0"/>'
    import math
    slices: list[str] = []
    cx, cy, r = 80, 80, 70
    start = -math.pi / 2
    for sev in _SEVERITY_ORDER:
        c = counts.get(sev, 0)
        if c == 0:
            continue
        angle = 2 * math.pi * c / total
        end = start + angle
        x1, y1 = cx + r * math.cos(start), cy + r * math.sin(start)
        x2, y2 = cx + r * math.cos(end), cy + r * math.sin(end)
        large = 1 if angle > math.pi else 0
        color = _SEVERITY_COLORS[sev]
        slices.append(
            f'<path d="M{cx},{cy} L{x1:.2f},{y1:.2f} A{r},{r} 0 {large},1 {x2:.2f},{y2:.2f} Z" fill="{color}"/>'
        )
        start = end
    slices.append(f'<circle cx="{cx}" cy="{cy}" r="35" fill="#f8fafc"/>')
    return "".join(slices)
