"""Markdown report generator for Sentinel findings."""
from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

from sentinel.reporters.base import BaseReporter

_SEV_EMOJI = {
    "critical": "🔴",
    "high": "🟠",
    "medium": "🟡",
    "low": "🟢",
    "info": "🔵",
}
_SEVERITY_ORDER = ["critical", "high", "medium", "low", "info"]


def _sev(f) -> str:
    return str(getattr(getattr(f, "severity", None), "value", getattr(f, "severity", "info"))).lower()


class MarkdownReporter(BaseReporter):
    """Generate a Markdown report with summary and findings table."""

    def generate(self, findings: list, metadata: dict[str, Any] | None = None) -> str:
        meta = metadata or {}
        scan_path = str(meta.get("scan_path", "."))
        tool_version = str(meta.get("tool_version", "Eresus Sentinel"))
        timestamp = meta.get("timestamp") or datetime.now(timezone.utc).isoformat()

        lines: list[str] = [
            "# 🛡️ Eresus Sentinel — Security Report",
            "",
            f"**Scan path:** `{scan_path}`  ",
            f"**Generated:** {timestamp}  ",
            f"**Tool:** {tool_version}  ",
            "",
        ]

        counts: dict[str, int] = {s: 0 for s in _SEVERITY_ORDER}
        for f in findings:
            counts[_sev(f)] = counts.get(_sev(f), 0) + 1

        lines.append("## Summary")
        lines.append("")
        lines.append("| Severity | Count |")
        lines.append("|----------|-------|")
        for sev in _SEVERITY_ORDER:
            emoji = _SEV_EMOJI.get(sev, "")
            lines.append(f"| {emoji} {sev.capitalize()} | {counts[sev]} |")
        lines.append(f"| **Total** | **{len(findings)}** |")
        lines.append("")

        if not findings:
            lines.append("## Findings")
            lines.append("")
            lines.append("✅ No findings — scan clean.")
            lines.append("")
        else:
            lines.append("## Findings")
            lines.append("")
            lines.append("| Severity | Rule ID | Title | Target | Description |")
            lines.append("|----------|---------|-------|--------|-------------|")
            sorted_findings = sorted(
                findings,
                key=lambda x: _SEVERITY_ORDER.index(_sev(x)) if _sev(x) in _SEVERITY_ORDER else 99,
            )
            for f in sorted_findings:
                sev = _sev(f)
                emoji = _SEV_EMOJI.get(sev, "")
                rule_id = str(getattr(f, "rule_id", ""))
                title = str(getattr(f, "title", "")).replace("|", "\\|")
                target = str(getattr(f, "target", "")).replace("|", "\\|")
                desc = str(getattr(f, "description", "")).replace("|", "\\|")
                if len(desc) > 120:
                    desc = desc[:117] + "..."
                lines.append(
                    f"| {emoji} {sev.upper()} | `{rule_id}` | {title} | `{target}` | {desc} |"
                )
            lines.append("")

        lines.append("---")
        lines.append("*Generated by Eresus Sentinel*")
        return "\n".join(lines)
